In [1]:
import numpy as np
import pandas as pd

In [2]:
string_data=pd.Series(['aardvark','artichoke',np.nan,'avocado'])

In [3]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [4]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data[0]=None

In [6]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [7]:
from numpy import nan as NA

In [8]:
data=pd.Series([1,NA,3.5,NA,7])

In [9]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data=pd.DataFrame([[1.,6.5,3.],[1.,NA,NA],[NA,NA,NA],[NA,6.5,3]])

In [12]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [13]:
cleaned=data.dropna()

In [14]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [15]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [16]:
data[4]=NA

In [17]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [18]:
data.dropna(axis=1,how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [19]:
df=pd.DataFrame(np.random.randn(7,3))

In [20]:
df.iloc[:4,1]=NA

In [21]:
df.iloc[:2,2]=NA

In [22]:
df

0         1         2
0  0.464151       NaN       NaN
1  0.181078       NaN       NaN
2 -0.429574       NaN  0.036390
3  0.531400       NaN  0.281256
4  0.212468 -1.489992  0.130997
5 -0.109069 -0.252816  0.480810
6 -1.108550 -0.080870  0.311686

In [23]:
df.dropna()

0         1         2
4  0.212468 -1.489992  0.130997
5 -0.109069 -0.252816  0.480810
6 -1.108550 -0.080870  0.311686

In [24]:
df.fillna(0)

0         1         2
0  0.464151  0.000000  0.000000
1  0.181078  0.000000  0.000000
2 -0.429574  0.000000  0.036390
3  0.531400  0.000000  0.281256
4  0.212468 -1.489992  0.130997
5 -0.109069 -0.252816  0.480810
6 -1.108550 -0.080870  0.311686

In [25]:
df.fillna({1:0.5,2:0})

0         1         2
0  0.464151  0.500000  0.000000
1  0.181078  0.500000  0.000000
2 -0.429574  0.500000  0.036390
3  0.531400  0.500000  0.281256
4  0.212468 -1.489992  0.130997
5 -0.109069 -0.252816  0.480810
6 -1.108550 -0.080870  0.311686

In [26]:
_=df.fillna(0,inplace=True)

In [27]:
df

0         1         2
0  0.464151  0.000000  0.000000
1  0.181078  0.000000  0.000000
2 -0.429574  0.000000  0.036390
3  0.531400  0.000000  0.281256
4  0.212468 -1.489992  0.130997
5 -0.109069 -0.252816  0.480810
6 -1.108550 -0.080870  0.311686

In [28]:
df=pd.DataFrame(np.random.randn(6,3))

In [29]:
df

0         1         2
0 -1.042563  2.285131  1.968926
1 -0.537329 -0.053626 -0.325010
2  0.012611  0.729780  0.623048
3  1.179768  0.876622  0.588338
4  0.573184 -1.267784 -0.121361
5 -0.706787 -0.502412  0.001316

In [30]:
df.iloc[2:,1]=NA

In [31]:
df

0         1         2
0 -1.042563  2.285131  1.968926
1 -0.537329 -0.053626 -0.325010
2  0.012611       NaN  0.623048
3  1.179768       NaN  0.588338
4  0.573184       NaN -0.121361
5 -0.706787       NaN  0.001316

In [32]:
df.iloc[4:,2]=NA

In [33]:
df

0         1         2
0 -1.042563  2.285131  1.968926
1 -0.537329 -0.053626 -0.325010
2  0.012611       NaN  0.623048
3  1.179768       NaN  0.588338
4  0.573184       NaN       NaN
5 -0.706787       NaN       NaN

In [34]:
df.fillna(method='ffill')

0         1         2
0 -1.042563  2.285131  1.968926
1 -0.537329 -0.053626 -0.325010
2  0.012611 -0.053626  0.623048
3  1.179768 -0.053626  0.588338
4  0.573184 -0.053626  0.588338
5 -0.706787 -0.053626  0.588338

In [35]:
df.fillna(method='ffill',limit=1)

0         1         2
0 -1.042563  2.285131  1.968926
1 -0.537329 -0.053626 -0.325010
2  0.012611 -0.053626  0.623048
3  1.179768       NaN  0.588338
4  0.573184       NaN  0.588338
5 -0.706787       NaN       NaN

In [36]:
data=pd.Series([1.,NA,3.5,NA,7])

In [37]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [38]:
data=pd.DataFrame({'k1':['one','two']*3+['two'],'k2':[1,1,2,3,3,4,4]})

In [39]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [40]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [41]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [42]:
data['v1']=range(7)

In [43]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [44]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [45]:
data.drop_duplicates(['k1','k2'],keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [46]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon','Pastrami', 'corned beef', 'Bacon',
                              'pastrami', 'honey ham', 'nova lox'],'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
  


In [47]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [48]:
meat_to_animal = {
      'bacon': 'pig',
      'pulled pork': 'pig',
      'pastrami': 'cow',
      'corned beef': 'cow',
      'honey ham': 'pig',
      'nova lox': 'salmon'
}

In [49]:
lowercased=data['food'].str.lower()

In [50]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [51]:
data['animal']=lowercased.map(meat_to_animal)

In [52]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [53]:
data['food'].map(lambda x:meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [54]:
data=pd.Series([1.,-999,2.,-999,-1000,3.])

In [55]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [56]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [57]:
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [58]:
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [59]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),index=['Ohio', 'Colorado', 'New York'],columns=['one', 'two', 'three', 'four'])

In [60]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [61]:
transform=lambda x:x[:4].upper()

In [62]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [63]:
data.index=data.index.map(transform)

In [64]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [65]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [66]:
bins = [18, 25, 35, 60, 100]

In [67]:
cats=pd.cut(ages,bins)

In [68]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [69]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [70]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [71]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [72]:
data=pd.DataFrame(np.random.randn(1000,4))

In [73]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.042601    -0.017087     0.017540    -0.012907
std       0.970117     1.039002     0.988263     0.986020
min      -3.415758    -3.246904    -3.654227    -2.915417
25%      -0.662354    -0.655992    -0.628594    -0.676350
50%      -0.039879    -0.004879     0.027015    -0.007342
75%       0.600142     0.657279     0.663442     0.702396
max       2.910831     3.171633     3.222510     2.776051

In [74]:
col=data[2]

In [75]:
col[np.abs(col)>3]

154    3.222510
464   -3.604023
997   -3.654227
Name: 2, dtype: float64

In [79]:
data[(np.abs(data)>3).any(1)]

0         1         2         3
150 -0.886688 -3.246904  0.846445  0.886009
154  0.058197  0.394076  3.222510 -0.018464
173  0.513841 -3.173002  0.533530 -2.179398
269 -3.415758 -0.415466  1.661512  0.611187
443  0.964732  3.105313  0.293506  0.415717
464 -0.621011  0.140753 -3.604023 -0.444081
657 -0.110069  3.171633  1.454577 -0.019976
997 -1.747874  0.546465 -3.654227  2.776051

In [80]:
data[np.abs(data)>3]=np.sign(data)*3

In [82]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.042185    -0.016944     0.018576    -0.012907
std       0.968758     1.036925     0.983306     0.986020
min      -3.000000    -3.000000    -3.000000    -2.915417
25%      -0.662354    -0.655992    -0.628594    -0.676350
50%      -0.039879    -0.004879     0.027015    -0.007342
75%       0.600142     0.657279     0.663442     0.702396
max       2.910831     3.000000     3.000000     2.776051

In [83]:
df=pd.DataFrame(np.arange(5*4).reshape((5,4)))

In [84]:
sampler=np.random.permutation(5)

In [85]:
sampler

array([4, 3, 1, 2, 0])

In [86]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [87]:
df.take(sampler)

0   1   2   3
4  16  17  18  19
3  12  13  14  15
1   4   5   6   7
2   8   9  10  11
0   0   1   2   3

In [88]:
df.sample(n=3)

0   1   2   3
4  16  17  18  19
0   0   1   2   3
2   8   9  10  11

In [89]:
choices=pd.Series([5,7,-1,6,4])

In [90]:
draws=choices.sample(n=10,replace=True)

In [91]:
draws

4    4
2   -1
0    5
1    7
2   -1
2   -1
0    5
1    7
2   -1
0    5
dtype: int64

In [92]:
df=pd.DataFrame({'key':['b','b','a','c','a','b'],'data1':range(6)})

In [93]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [95]:
dummies=pd.get_dummies(df['key'],prefix='key')

In [96]:
df_with_dummy=df[['data1']].join(dummies)

In [97]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [101]:
a=np.random.seed(12345)

In [102]:
values=np.random.rand(10)

In [103]:
values

array([ 0.92961609,  0.31637555,  0.18391881,  0.20456028,  0.56772503,
        0.5955447 ,  0.96451452,  0.6531771 ,  0.74890664,  0.65356987])

In [105]:
print(a)

None


In [106]:
bins=[0,0.2,0.4,0.6,0.8,1]

In [107]:
pd.get_dummies(pd.cut(values,bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

In [108]:
val = 'a,b,  guido'

In [110]:
data=pd.Series(np.random.randn(9),index=[['a','a','a','b','b','c','c','d','d'],[1,2,3,1,3,1,2,2,3]])

In [111]:
data

a  1    1.007189
   2   -1.296221
   3    0.274992
b  1    0.228913
   3    1.352917
c  1    0.886429
   2   -2.001637
d  2   -0.371843
   3    1.669025
dtype: float64

In [112]:
data.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 2, 0, 1, 1, 2]])

In [113]:
data['b']

1    0.228913
3    1.352917
dtype: float64

In [114]:
data['b':'c']

b  1    0.228913
   3    1.352917
c  1    0.886429
   2   -2.001637
dtype: float64

In [115]:
data.loc[['b','d']]

b  1    0.228913
   3    1.352917
d  2   -0.371843
   3    1.669025
dtype: float64

In [116]:
data.unstack()

1         2         3
a  1.007189 -1.296221  0.274992
b  0.228913       NaN  1.352917
c  0.886429 -2.001637       NaN
d       NaN -0.371843  1.669025

In [117]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                     columns=[['Ohio', 'Ohio', 'Colorado'],['Green', 'Red', 'Green']])

In [118]:
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [119]:
frame.index.names=['key1','key2']

In [120]:
frame.columns.names=['state','color']

In [121]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11