In [1]:
import numpy as np
import pandas as pd

In [2]:
obj=pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])

In [3]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [4]:
obj2=obj.reindex(['a','b','c','d','e'])

In [5]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [6]:
obj3=pd.Series(['blue','purple','yellow'],index=[0,2,4])

In [7]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [8]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [9]:
frame=pd.DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],columns=['Ohio','Texas','California'])

In [10]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [11]:
frame2=frame.reindex(['a','b','c','d'])

In [12]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [13]:
states=['Texas','Utah','California']

In [14]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [15]:
obj=pd.Series(np.arange(5.),index=['a','b','c','d','e'])

In [16]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [17]:
new_obj=obj.drop('c')

In [18]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [19]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [20]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','CC','DD','EE'],columns=['one','two','three','four'])

In [21]:
data

one  two  three  four
Ohio    0    1      2     3
CC      4    5      6     7
DD      8    9     10    11
EE     12   13     14    15

In [22]:
data.drop(['CC','DD'])

one  two  three  four
Ohio    0    1      2     3
EE     12   13     14    15

In [29]:
data.drop('three',axis=1)

one  two  four
Ohio    0    1     3
CC      4    5     7
DD      8    9    11
EE     12   13    15

In [30]:
data.drop(['two','four'],axis='columns')

one  three
Ohio    0      2
CC      4      6
DD      8     10
EE     12     14

In [31]:
obj=pd.Series(np.arange(4.),index=['a','b','c','d'])

In [32]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [33]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),index=['Ohio', 'Colorado', 'Utah', 'New York'],columns=['one', 'two', 'three', 'four'])

In [34]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [35]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int64

In [36]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [37]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [38]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    4    5
Utah        11    8    9

In [39]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [40]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [41]:
ser=pd.Series(np.arange(3.))

In [42]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [44]:
ser2=pd.Series(np.arange(3.),index=['a','b','c'])

In [45]:
ser2[-1]

2.0

In [46]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [47]:
ser[:1]

0    0.0
dtype: float64

In [48]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [49]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],index=['a', 'c', 'e', 'f', 'g'])

In [50]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [51]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [52]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [53]:
df1=pd.DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),index=['Ohio','Texas','Colorado'])

In [54]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [56]:
df2=pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [57]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [58]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [59]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [60]:
df1=pd.DataFrame({'A':[1,2]})

In [61]:
df1

A
0  1
1  2

In [62]:
df2=pd.DataFrame({'B':[3,4]})

In [63]:
df2

B
0  3
1  4

In [64]:
df1-df2

A   B
0 NaN NaN
1 NaN NaN

In [66]:
df1=pd.DataFrame(np.arange(12.).reshape((3,4)),columns=list('abcd'))

In [70]:
df2=pd.DataFrame(np.arange(20.).reshape((4,5)),columns=list('abcde'))

In [71]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [73]:
df2.loc[1,'b']=np.nan

In [74]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [75]:
df2+df1

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [77]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [78]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [79]:
arr=np.arange(12.).reshape((3,4))

In [80]:
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [81]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [82]:
arr-arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [83]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),columns=list('bde'),index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [84]:
series=frame.iloc[0]

In [85]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [86]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [87]:
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [88]:
frame=pd.DataFrame(np.random.randn(4,3),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [89]:
frame

b         d         e
Utah   -1.491293 -0.572981  0.025037
Ohio    1.127163  0.729356  0.147951
Texas   0.250669 -0.786476 -0.496323
Oregon  0.006654  1.055514  1.093798

In [90]:
np.abs(frame)

b         d         e
Utah    1.491293  0.572981  0.025037
Ohio    1.127163  0.729356  0.147951
Texas   0.250669  0.786476  0.496323
Oregon  0.006654  1.055514  1.093798

In [96]:
f=lambda x:x.max()-x.min()

In [97]:
f

<function __main__.<lambda>>

In [98]:
print(f)

<function <lambda> at 0x1188ff2f0>


In [99]:
frame.apply(f)

b    2.618456
d    1.841991
e    1.590122
dtype: float64

In [100]:
frame.apply(f,axis='columns')

Utah      1.516330
Ohio      0.979213
Texas     1.037146
Oregon    1.087145
dtype: float64

In [101]:
frame

b         d         e
Utah   -1.491293 -0.572981  0.025037
Ohio    1.127163  0.729356  0.147951
Texas   0.250669 -0.786476 -0.496323
Oregon  0.006654  1.055514  1.093798

In [102]:
obj=pd.Series(range(4),index=['d','a','b','c'])

In [103]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [104]:
frame=pd.DataFrame(np.arange(8).reshape((2,4)),index=['three','one'],columns=['d','a','b','c'])

In [105]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [108]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [109]:
obj=pd.Series([4,7,-3,2])

In [110]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [111]:
frame=pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

In [112]:
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [113]:
frame.sort_values(by='b')

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [114]:
frame.sort_values(by=['a','b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [115]:
df=pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],index=['a','b','c','d'],columns=['one','two'])

In [116]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [117]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [118]:
df.sum(axis='columns')

a    1.40
b    2.60
c     NaN
d   -0.55
dtype: float64

In [119]:
df.mean(axis='columns',skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [120]:
df.idxmax()

one    b
two    d
dtype: object

In [121]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [122]:
import pandas_datareader.data as web

In [124]:
all_data={ticker:web.get_data_yahoo(ticker) for ticker in ['AAPL','IBM','MSFT','GOOG']}
price = pd.DataFrame({ticker: data['Adj Close'] for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume'] for ticker, data in all_data.items()})

In [125]:
returns=price.pct_change()

In [126]:
returns.tail()

AAPL      GOOG       IBM      MSFT
Date                                              
2019-06-17  0.005967  0.006588 -0.001480  0.003020
2019-06-18  0.023518  0.010160  0.010597  0.017388
2019-06-19 -0.002923 -0.001151  0.005133  0.003921
2019-06-20  0.008036  0.008246  0.012912  0.009286
2019-06-21 -0.003409  0.009411  0.002521  0.000146

In [129]:
returns['MSFT'].corr(returns['IBM'])

0.48705046285871689